### ISSUE TITLE
NPM Run issue

### ISSUE THREAD

**Issue by pawansinha0612** [christian-bromann/webdriverio-performance-testing#5]
Hi Christian,
Thanks for this repo. I am following the steps and i a stuck in running the NPM and getting below error. can you please help.

$ npm test

> webdriverio-performance-testing@0.0.1 test c:\NotBackedUp\test\webdriverio-performance-testing
> echo 'Error: no test specified'

**Comment by christian-bromann** [comment]
The following NPM commands are defined: https://github.com/christian-bromann/webdriverio-performance-testing/blob/master/package.json#L7-L8

**Comment by pawansinha0612** [comment]
I already have this when I pulled that code - I am just following your steps. and it's failing while doing npm test.

The link which you have given, I already have that command in package.json
Let me know if it requires any pre-requisite to install chrome drivers.

$npm test
webdriverio-performance-testing@0.0.1 test c:\NotBackedUp\test\webdriverio-performance-testing
echo 'Error: no test specified'

**Comment by christian-bromann** [comment]
@pawansinha0612 I updated the readme, please use `$ npm run test:local`

**Comment by pawansinha0612** [comment]
Thanks Christian, I progressed little.

But still stucked with the below error: Please help
```
$ npm run test:local

> webdriverio-performance-testing@0.0.1 test:local c:\NotBackedUp\test\webdriverio-performance-testing
> wdio wdio.local.conf.js


Execution of 2 spec files started at 2020-03-20T09:26:17.922Z

Starting ChromeDriver 80.0.3987.16 (320f6526c1632ad4f205ebce69b99a062ed78647-refs/branch-heads/3987@{#185}) on port 9515
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
[0-1] RUNNING in chrome - c:\NotBackedUp\test\webdriverio-performance-testing\tests\performance.test.js
[0-0] RUNNING in chrome - c:\NotBackedUp\test\webdriverio-performance-testing\tests\resource.test.js
[11616:14892:0320/202629.111:ERROR:configuration_policy_handler_list.cc(90)] Unknown policy: AlwaysAuthorizePlugins
[7620:14176:0320/202629.111:ERROR:configuration_policy_handler_list.cc(90)] Unknown policy: AlwaysAuthorizePlugins
[11616:14892:0320/202629.111:ERROR:configuration_policy_handler_list.cc(90)] Unknown policy: DefaultKeygenSetting
[7620:14176:0320/202629.111:ERROR:configuration_policy_handler_list.cc(90)] Unknown policy: DefaultKeygenSetting
[11616:14892:0320/202629.113:ERROR:configuration_policy_handler_list.cc(90)] Unknown policy: DisablePluginFinder
[7620:14176:0320/202629.113:ERROR:configuration_policy_handler_list.cc(90)] Unknown policy: DisablePluginFinder
[11616:14892:0320/202629.113:ERROR:configuration_policy_handler_list.cc(90)] Unknown policy: DisableSSLRecordSplitting
[7620:14176:0320/202629.113:ERROR:configuration_policy_handler_list.cc(90)] Unknown policy: DisableSSLRecordSplitting
[11616:14892:0320/202629.113:ERROR:configuration_policy_handler_list.cc(90)] Unknown policy: EnableCommonNameFallbackForLocalAnchors
[7620:14176:0320/202629.113:ERROR:configuration_policy_handler_list.cc(90)] Unknown policy: EnableCommonNameFallbackForLocalAnchors
[11616:14892:0320/202629.113:ERROR:configuration_policy_handler_list.cc(90)] Unknown policy: EnableSha1ForLocalAnchors
[11616:14892:0320/202629.113:ERROR:configuration_policy_handler_list.cc(90)] Unknown policy: HideWebStorePromo
[7620:14176:0320/202629.113:ERROR:configuration_policy_handler_list.cc(90)] Unknown policy: EnableSha1ForLocalAnchors
[11616:14892:0320/202629.114:ERROR:configuration_policy_handler_list.cc(90)] Unknown policy: SupervisedUserCreationEnabled
[7620:14176:0320/202629.114:ERROR:configuration_policy_handler_list.cc(90)] Unknown policy: HideWebStorePromo
[7620:14176:0320/202629.116:ERROR:configuration_policy_handler_list.cc(90)] Unknown policy: SupervisedUserCreationEnabled
[7620:14176:0320/202629.894:ERROR:configuration_policy_handler_list.cc(90)] Unknown policy: AlwaysAuthorizePlugins
[11616:14892:0320/202629.895:ERROR:configuration_policy_handler_list.cc(90)] Unknown policy: AlwaysAuthorizePlugins
[7620:14176:0320/202629.898:ERROR:configuration_policy_handler_list.cc(90)] Unknown policy: DefaultKeygenSetting
[11616:14892:0320/202629.899:ERROR:configuration_policy_handler_list.cc(90)] Unknown policy: DefaultKeygenSetting
[7620:14176:0320/202629.899:ERROR:configuration_policy_handler_list.cc(90)] Unknown policy: DisablePluginFinder
[11616:14892:0320/202629.899:ERROR:configuration_policy_handler_list.cc(90)] Unknown policy: DisablePluginFinder
[7620:14176:0320/202629.899:ERROR:configuration_policy_handler_list.cc(90)] Unknown policy: DisableSSLRecordSplitting
[11616:14892:0320/202629.899:ERROR:configuration_policy_handler_list.cc(90)] Unknown policy: DisableSSLRecordSplitting
[7620:14176:0320/202629.899:ERROR:configuration_policy_handler_list.cc(90)] Unknown policy: EnableCommonNameFallbackForLocalAnchors
[11616:14892:0320/202629.900:ERROR:configuration_policy_handler_list.cc(90)] Unknown policy: EnableCommonNameFallbackForLocalAnchors
[7620:14176:0320/202629.900:ERROR:configuration_policy_handler_list.cc(90)] Unknown policy: EnableSha1ForLocalAnchors
[11616:14892:0320/202629.900:ERROR:configuration_policy_handler_list.cc(90)] Unknown policy: EnableSha1ForLocalAnchors
[7620:14176:0320/202629.900:ERROR:configuration_policy_handler_list.cc(90)] Unknown policy: HideWebStorePromo
[11616:14892:0320/202629.900:ERROR:configuration_policy_handler_list.cc(90)] Unknown policy: HideWebStorePromo
[7620:14176:0320/202629.902:ERROR:configuration_policy_handler_list.cc(90)] Unknown policy: SupervisedUserCreationEnabled
[11616:14892:0320/202629.902:ERROR:configuration_policy_handler_list.cc(90)] Unknown policy: SupervisedUserCreationEnabled

DevTools listening on ws://127.0.0.1:4680/devtools/browser/87e0175a-27b6-4b65-b9b7-cb5a5b4b258c

DevTools listening on ws://127.0.0.1:4681/devtools/browser/6365607c-e4d7-4373-91e0-5df1539dc6dc
[1584696434.683][SEVERE]: Timed out receiving message from renderer: 0.100
[1584696435.661][SEVERE]: Timed out receiving message from renderer: 0.100
[1584696435.769][SEVERE]: Timed out receiving message from renderer: 0.100
[1584696435.875][SEVERE]: Timed out receiving message from renderer: 0.100
[1584696435.981][SEVERE]: Timed out receiving message from renderer: 0.100
[0-0] TypeError in "pageWeight images should be compressed"
Cannot read property 'encoded' of undefined
[0-0] FAILED in chrome - c:\NotBackedUp\test\webdriverio-performance-testing\tests\resource.test.js
[0-1] AssertionError in "My Performance Test should not increase firstInteractive limi"
expected 3129 to be below 3000
[0-1] AssertionError in "My Performance Test should have a minimum Lighthouse performance score"
expected 0.877837101396931 to be above 0.92
[448.442] ing_service_impl.cc:578 Configured tracing, #sources:2, duration:0 ms, #buffers:1, total buffer size:204800 KB, total sessions:1
[462.257] ng_service_impl.cc:1719 Tracing session 1 ended, total sessions:0
[0-1] FAILED in chrome - c:\NotBackedUp\test\webdriverio-performance-testing\tests\performance.test.js

 "spec" Reporter:
------------------------------------------------------------------
[chrome  windows #0-0] Spec: c:\NotBackedUp\test\webdriverio-performance-testing\tests\resource.test.js
[chrome  windows #0-0] Running: chrome on windows
[chrome  windows #0-0] Session ID: d7c9e46574818709fee66b6fac614664
[chrome  windows #0-0]
[chrome  windows #0-0] pageWeight
[chrome  windows #0-0]    ✓ should load not more than 450kb
[chrome  windows #0-0]    ✖ images should be compressed
[chrome  windows #0-0]    ✓ scripts should be minified
[chrome  windows #0-0]
[chrome  windows #0-0] 2 passing (27.5s)
[chrome  windows #0-0] 1 failing
[chrome  windows #0-0]
[chrome  windows #0-0] 1) pageWeight images should be compressed
[chrome  windows #0-0] Cannot read property 'encoded' of undefined
[chrome  windows #0-0] TypeError: Cannot read property 'encoded' of undefined
[chrome  windows #0-0]     at Context.it (c:\NotBackedUp\test\webdriverio-performance-testing\tests/resource.test.js:23:30)
[chrome  windows #0-0]     at Context.executeSync (c:\NotBackedUp\test\webdriverio-performance-testing\node_modules\@wdio\sync\build\index.js:56:18)
[chrome  windows #0-0]     at c:\NotBackedUp\test\webdriverio-performance-testing\node_modules\@wdio\sync\build\index.js:82:70
------------------------------------------------------------------
[chrome  windows #0-1] Spec: c:\NotBackedUp\test\webdriverio-performance-testing\tests\performance.test.js
[chrome  windows #0-1] Running: chrome on windows
[chrome  windows #0-1] Session ID: 0c487179506284f233bcf9974f051ec5
[chrome  windows #0-1]
[chrome  windows #0-1] My Performance Test
[chrome  windows #0-1]    ✓ should not increase firstMeaningfulPaint limit
[chrome  windows #0-1]    ✖ should not increase firstInteractive limi
[chrome  windows #0-1]    ✓ should not increase speedIndex limit
[chrome  windows #0-1]    ✖ should have a minimum Lighthouse performance score
[chrome  windows #0-1]
[chrome  windows #0-1] 2 passing (29.5s)
[chrome  windows #0-1] 2 failing
[chrome  windows #0-1]
[chrome  windows #0-1] 1) My Performance Test should not increase firstInteractive limi
[chrome  windows #0-1] expected 3129 to be below 3000
[chrome  windows #0-1] AssertionError: expected 3129 to be below 3000
[chrome  windows #0-1]     at Context.<anonymous> (c:\NotBackedUp\test\webdriverio-performance-testing\tests/performance.test.js:18:48)
[chrome  windows #0-1]     at Context.executeSync (c:\NotBackedUp\test\webdriverio-performance-testing\node_modules\@wdio\sync\build\index.js:56:18)
[chrome  windows #0-1]     at c:\NotBackedUp\test\webdriverio-performance-testing\node_modules\@wdio\sync\build\index.js:82:70
[chrome  windows #0-1]
[chrome  windows #0-1] 2) My Performance Test should have a minimum Lighthouse performance score
[chrome  windows #0-1] expected 0.877837101396931 to be above 0.92
[chrome  windows #0-1] AssertionError: expected 0.877837101396931 to be above 0.92
[chrome  windows #0-1]     at Context.it (c:\NotBackedUp\test\webdriverio-performance-testing\tests/performance.test.js:26:29)
[chrome  windows #0-1]     at Context.executeSync (c:\NotBackedUp\test\webdriverio-performance-testing\node_modules\@wdio\sync\build\index.js:56:18)
[chrome  windows #0-1]     at c:\NotBackedUp\test\webdriverio-performance-testing\node_modules\@wdio\sync\build\index.js:82:70


Spec Files:      0 passed, 2 failed, 2 total (100% completed) in 00:01:09

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webdriverio-performance-testing@0.0.1 test:local: `wdio wdio.local.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webdriverio-performance-testing@0.0.1 test:local script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sinhap3\AppData\Roaming\npm-cache\_logs\2020-03-20T09_27_28_362Z-debug.log
```

**Comment by christian-bromann** [comment]
> But still stucked with the below error:

This is not an error. The test fail because the performance is above the treshold.
