### ISSUE TITLE
Browser.getMetrics() is not a function

### ISSUE THREAD

**Issue by pratimghosh76** [christian-bromann/webdriverio-performance-testing#7]
I am getting browser.getMetrics is not a function error
not sure if some one was successfully able to get the results. please share the package.json for this

Below is my package.json

below is my package.json
"dependencies": {
    "@babel/cli": "^7.8.4",
    "@babel/core": "^7.9.6",
    "@babel/preset-env": "^7.9.6",
    "@babel/register": "^7.9.0",
    "@slack/client": "^5.0.2",
    "@wdio/devtools-service": "6.3.7",
    "@wdio/local-runner": "^6.1.12",
    "@wdio/mocha-framework": "^6.1.8",
    "@wdio/selenium-standalone-service": "^6.4.7",
    "@wdio/spec-reporter": "^6.4.7",
    "@wdio/sync": "^6.1.8",
    "chai": "^4.2.0",
    "chromedriver": "^83.0.0",
    "chromium": "^3.0.2",
    "csv-write-stream": "^2.0.0",
    "fs": "0.0.1-security",
    "https": "^1.0.0",
    "node-localstorage": "^2.1.6",
    "node-slack": "0.0.7",
    "puppeteer": "3.0.1",
    "puppeteer-core": "2.0.0",
    "slack": "^11.0.2",
    "tcp-port-used": "^1.0.1",
    "url": "^0.11.0",
    "wdio-chromedriver-service": "^5.0.1",
    "webdriverio": "5.23.0"
  },
  "devDependencies": {
    "@wdio/cli": "^6.1.12",
    "@wdio/sauce-service": "^6.5.0",
    "chakram": "^1.5.0",
    "wdio-docker-service": "^3.0.0",
    "wdio-json-reporter": "^2.0.0",
    "wdio-slack-service": "^2.0.8"
  }

**Comment by christian-bromann** [comment]
Can you share some WebdriverIO logs?

**Comment by pratimghosh76** [comment]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/pxg8q0v/.nvm/versions/node/v12.18.3/bin/node',
1 verbose cli   '/Users/pxg8q0v/.nvm/versions/node/v12.18.3/bin/npm',
1 verbose cli   'run',
1 verbose cli   'test:local'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.3
4 verbose run-script [ 'pretest:local', 'test:local', 'posttest:local' ]
5 info lifecycle homedepot-performance-testing@1.0.0~pretest:local: homedepot-performance-testing@1.0.0
6 info lifecycle homedepot-performance-testing@1.0.0~test:local: homedepot-performance-testing@1.0.0
7 verbose lifecycle homedepot-performance-testing@1.0.0~test:local: unsafe-perm in lifecycle true
8 verbose lifecycle homedepot-performance-testing@1.0.0~test:local: PATH: /Users/pxg8q0v/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/pxg8q0v/git/gm_perftest/node_modules/.bin:/Users/pxg8q0v/.nvm/versions/node/v12.18.3/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Users/pxg8q0v/.jenv/shims:/Users/pxg8q0v/.jenv/bin:/Users/pxg8q0v/.jenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Users/pxg8q0v/.jenv/shims:/Users/pxg8q0v/.jenv/bin:/tmp/build//Users/pxg8q0v/git/gm_perftest/gm_perftest/nodemodules/chromedriver:/tmp/build//gm_perftest/nodemodules/chromedriver
9 verbose lifecycle homedepot-performance-testing@1.0.0~test:local: CWD: /Users/pxg8q0v/git/gm_perftest
10 silly lifecycle homedepot-performance-testing@1.0.0~test:local: Args: [ '-c', 'wdio wdio.local.conf.js' ]
11 silly lifecycle homedepot-performance-testing@1.0.0~test:local: Returned: code: 1  signal: null
12 info lifecycle homedepot-performance-testing@1.0.0~test:local: Failed to exec test:local script
13 verbose stack Error: homedepot-performance-testing@1.0.0 test:local: `wdio wdio.local.conf.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/pxg8q0v/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/Users/pxg8q0v/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid homedepot-performance-testing@1.0.0
15 verbose cwd /Users/pxg8q0v/git/gm_perftest
16 verbose Darwin 18.7.0
17 verbose argv "/Users/pxg8q0v/.nvm/versions/node/v12.18.3/bin/node" "/Users/pxg8q0v/.nvm/versions/node/v12.18.3/bin/npm" "run" "test:local"
18 verbose node v12.18.3
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error homedepot-performance-testing@1.0.0 test:local: `wdio wdio.local.conf.js`
22 error Exit status 1
23 error Failed at the homedepot-performance-testing@1.0.0 test:local script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by pratimghosh76** [comment]
another strange thing, some how it worked for me. but suddenly everything stopped working. below is the package.json file which was working for me
"dependencies": {
    "@babel/cli": "^7.8.4",
    "@babel/core": "^7.9.6",
    "@babel/preset-env": "^7.9.6",
    "@babel/register": "^7.9.0",
    "@slack/client": "^5.0.2",
    "@wdio/devtools-service": "6.3.7",
    "@wdio/local-runner": "^6.1.12",
    "@wdio/mocha-framework": "^6.1.8",
    "@wdio/selenium-standalone-service": "^6.4.7",
    "@wdio/spec-reporter": "^6.4.7",
    "@wdio/sync": "^6.1.8",
    "chai": "^4.2.0",
    "chromium": "^3.0.2",
    "csv-write-stream": "^2.0.0",
    "fs": "0.0.1-security",
    "https": "^1.0.0",
    "node-localstorage": "^2.1.6",
    "node-slack": "0.0.7",
    "puppeteer": "3.0.1",
    "puppeteer-core": "2.0.0",
    "slack": "^11.0.2",
    "tcp-port-used": "^1.0.1",
    "url": "^0.11.0",
    "webdriverio": "6.1.12"
  },
  "devDependencies": {
    "@wdio/cli": "6.1.12",
    "@wdio/sauce-service": "^6.5.0",
    "chakram": "^1.5.0",
    "chromedriver": "^85.0.0",
    "wdio-chromedriver-service": "^6.0.3",
    "wdio-docker-service": "^3.0.0",
    "wdio-json-reporter": "^2.0.0",
    "wdio-slack-service": "^2.0.8"
  }

**Comment by christian-bromann** [comment]
@pratimghosh76 these are NPM logs which don't help that much, can you provide the WebdriverIO logs?

**Comment by Vishnu1067** [comment]
+1

**Comment by christian-bromann** [comment]
@Vishnu1067 how should we understand your `+1`?

**Comment by christian-bromann** [comment]
Closing due to inactivity.
